# --> server config:
server:
  port: 8080

spring:
# --> application config:
  application:
    name: mocktail

# --> hibernate config:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# --> datasource config:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

# --> mcp server config:
  ai:
   mcp:
     server:
       type: sync
       name: mocktail
       version: 1.0.0
       protocol: streamable
       streamable-http:
         mcp-endpoint: /mcp
         disallow-delete: true

# --> web config:
  main:
    web-application-type: servlet
    banner-mode: off

# --> actuator config:
management:
  endpoints:
    web:
      exposure:
        include: "*"


kind: Application
